export const CHOOSE_FILM = 'CHOOSE_FILM';
export const CHANGE_SELECTED_MOVIE_LIKES = 'CHANGE_SELECTED_MOVIE_LIKES';
export const CHANGE_SELECTED_MOVIE_STARS = 'CHANGE_SELECTED_MOVIE_STARS';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SHOW_ACTOR = 'SHOW_ACTOR';
